spring:
  application:
    name: config-production
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
   preferIpAddress: true
